Registrar/Controllers/CoursesController.cs
using Microsoft.AspNetCore.Mvc;
using Registrar.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Registrar.Controllers
{
  public class CoursesController : Controller
  {
    private readonly RegistrarContext _db;

    public CoursesController(RegistrarContext db)
    {
      _db = db;
    }

    public ActionResult Index(string CourseSearch)
    {
      List<Course> model = _db.Courses.ToList();
      if(CourseSearch!=null){
          model = _db.Courses.Where(courses => courses.CourseName.Contains(CourseSearch)).ToList();
        }
      return View(model);
    }

    public ActionResult Create()
    {

      // if(department==null){
      // return View()
      //   } else {
      //   _db.Departments.Add(department);
      //   _db.SaveChanges();
      //   }
      ViewBag.DepartmentId = new SelectList(_db.Departments, "DepartmentId", "DepartmentName");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Course course)
    {
      _db.Courses.Add(course);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisCourse = _db.Courses
        .Include(course => course.Students)
        .ThenInclude(join => join.Student)
        .FirstOrDefault(course => course.CourseId == id);
      return View(thisCourse);
    }

    public ActionResult Edit(int id)
    {
      var thisCourse = _db.Courses.FirstOrDefault(course => course.CourseId == id);
      return View(thisCourse);
    }

    [HttpPost]
    public ActionResult Edit(Course course)
    {
      _db.Entry(course).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult AddStudent(int id)
    {
        var thisCourse = _db.Courses.FirstOrDefault(course => course.CourseId == id);
        ViewBag.StudentId = new SelectList(_db.Students, "StudentId", "StudentName");
        return View(thisCourse);
    }
    [HttpPost]
    public ActionResult AddStudent(Course course, int StudentId)
    {
        if (StudentId != 0)
        {
            _db.CourseStudent.Add(new CourseStudent() { CourseId = course.CourseId, StudentId = StudentId });   
        }
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
        var thisCourse = _db.Courses.FirstOrDefault(courses => courses.CourseId == id);
        return View(thisCourse);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
        var thisCourse = _db.Courses.FirstOrDefault(courses => courses.CourseId == id);
        _db.Courses.Remove(thisCourse);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

    public ActionResult DeleteAll()
    {
        var allCourses = _db.Courses.ToList();
        return View();
    }

    [HttpPost, ActionName("DeleteAll")]
        public ActionResult DeleteAllConfirmed()
    {
        var allCourses = _db.Courses.ToList();

    foreach (var course in allCourses)
    {
        _db.Courses.Remove(course);
    }
        _db.SaveChanges();
        return RedirectToAction("Index");
    }
  }
}

Registrar/Controllers/StudentsController.cs
using Microsoft.AspNetCore.Mvc;
using Registrar.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Registrar.Controllers
{
    public class StudentsController : Controller
    {
        private readonly RegistrarContext _db;

        public StudentsController(RegistrarContext db)
        {
            _db = db;
        }

        public ActionResult Index(string StudentSearch)
        {
            List<Student> model = _db.Students.ToList();
            var sortedStudents = model.OrderBy( x => x.DateOfEnrollement.Year);
            var listAgain = sortedStudents.ToList();
            if (StudentSearch!=null) {
                listAgain = _db.Students.Where(students => students.StudentName.Contains(StudentSearch)).ToList();
                }
            return View(listAgain);
        }

        public ActionResult Details(int id)
        {
            var thisStudent = _db.Students
            .Include(student => student.Courses)
            .ThenInclude(join=>join.Course)
            .FirstOrDefault(student=>student.StudentId==id);
            return View(thisStudent);
        }

        public ActionResult Create()
        {
            ViewBag.CourseId = new SelectList(_db.Courses, "CourseId", "CourseName");
            return View();
        }
        [HttpPost]
        public ActionResult Create(Student student, int CourseId)
        {
            _db.Students.Add(student);
            if (CourseId != 0)
            {
                _db.CourseStudent.Add(new CourseStudent() { CourseId = CourseId, StudentId = student.StudentId});
            }
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var thisStudent = _db.Students.FirstOrDefault(students => students.StudentId == id);
            ViewBag.CourseId = new SelectList(_db.Courses, "CourseId", "CourseName");
            return View(thisStudent);
        }

        [HttpPost]
        public ActionResult Edit(Student student)
        {
            _db.Entry(student).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            var thisStudent = _db.Students.FirstOrDefault(students => students.StudentId == id);
            return View(thisStudent);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult Deleteconfirmed(int id)
        {
            var thisStudent = _db.Students.FirstOrDefault(students => students.StudentId == id);
            _db.Students.Remove(thisStudent);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult AddCourse(int id)
        {
            var thisStudent = _db.Students.FirstOrDefault(students => students.StudentId == id);
            ViewBag.CourseId = new SelectList(_db.Courses, "CourseId", "CourseName");
            return View(thisStudent);
        }
        [HttpPost]
        public ActionResult AddCourse(Student student, int CourseId)
        {
            if (CourseId != 0)
            {
                _db.CourseStudent.Add(new CourseStudent() { CourseId = CourseId, StudentId = student.StudentId });
            }
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult DeleteCourse(int joinId)
        {
            var joinEntry = _db.CourseStudent.FirstOrDefault(entry=>entry.CourseStudentId == joinId);
            _db.CourseStudent.Remove(joinEntry);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DeleteAll()
        {
            var allStudents = _db.Students.ToList();
            return View();
        }

        [HttpPost, ActionName("DeleteAll")]
            public ActionResult DeleteAllConfirmed()
        {
            var allStudents = _db.Students.ToList();

        foreach (var student in allStudents)
        {
            _db.Students.Remove(student);
        }
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Registrar/Views/Courses/AddStudent.cshtml
@{
  Layout = "_Layout";
}

@model Registrar.Models.Course
<div class="container card">
<h2>Add a student</h2>
<h4>Add a student to this course: @Html.DisplayFor(model => model.CourseName)</h4>

@using(Html.BeginForm())
{
  @Html.HiddenFor(model => model.CourseId)

  @Html.Label("Select student")
  @Html.DropDownList("StudentId")

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to courses", "Index")</p>\
</div>

Registrar/Views/Courses/Create.cshtml
@{
  Layout = "_Layout";
}

@model Registrar.Models.Course
<div class="container card">
<h4>Add a new course</h4>
@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.CourseId)

    @Html.TextBoxFor(model => model.CourseName)
    @Html.LabelFor(model => model.CourseName)
    <br>
    @Html.DropDownList("DepartmentId", (SelectList)ViewBag.DepartmentId, "-No department-")
    @Html.Label("Add department")
    <br>
    <input type="submit" value="Add new course" />
}
<p>@Html.ActionLink("Show all courses", "Index")</p>
</div>

Registrar/Views/Courses/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Registrar.Models.Course
<div class="container card">
<h2>Are you sure?</h2>

@Html.DisplayNameFor(model => model.CourseName) : @Html.DisplayFor(model => model.CourseName)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to course list", "Index")
</div>

Registrar/Views/Courses/Details.cshtml
@{
    Layout = "_Layout";
}

@model Registrar.Models.Course;
<div class="container card">
<h2>Course Details</h2>

<h3>@Html.DisplayNameFor(model => model.CourseName): @Html.DisplayFor(model => model.CourseName)</h3>

@if(@Model.Students.Count == 0)
{
    <p>This course does not have any students</p>
}
else
{
    <h3>Students this course contains:</h3>
    <ul>
    @foreach(var join in Model.Students)
    {
        <li>@Html.ActionLink(@join.Student.StudentName, "Details", "Students", new { id = join.StudentId })</li>
    }
    </ul>
}

<p>@Html.ActionLink("Add student to this course", "AddStudent", "Courses", new { id = Model.CourseId })</p>
<p>@Html.ActionLink("Back to courses", "Index")</p>
<p>@Html.ActionLink("Edit Course", "Edit", new { id = Model.CourseId })</p>
<p>@Html.ActionLink("Delete Course", "Delete", new { id = Model.CourseId })</p>
</div>

Registrar/Views/Courses/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Registrar.Models.Course
<div class="container card">
<h2>Edit</h2>

<h4>Edit this course: @Html.DisplayFor(model => model.CourseName)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.CourseId)

    @Html.LabelFor(model => model.CourseName)
    @Html.EditorFor(model => model.CourseName)

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to course list", "Index")</p>
</div>

Registrar/Views/Courses/Index.cshtml
@{
  Layout = "_Layout";
}

@using Registrar.Models;
@model List<Registrar.Models.Course>;
<div class="container card">
<h1>Courses</h1>
<form>
    <i class="glyphicon glyphicon-search"></i><input type="text" name="CourseSearch" placeholder="search and press enter">
</form>

@if (@Model.Count == 0)
{
    <h3>No courses have been added.</h3>
}

@if (ViewBag.Departments == 0) // check syntax
{
    <h3>No courses can be added until departments have been added. No departments yet exist.</h3>
    <p>@Html.ActionLink("Add new department", "Departments/Create")</p>//check Departments/Create syntax
}
else
{
@foreach (Course course in Model)
{
    <li>@Html.ActionLink($"{course.CourseName}", "Details", new { id = course.CourseId })</li>
}

<p>@Html.ActionLink("Add new course", "Create")</p>
}

<strong><p>@Html.ActionLink("Delete All Courses", "DeleteAll")</p></strong>
</div>