Registrar/Models/Department.cs
using System.Collections.Generic;

namespace Registrar.Models
{
  public class Department
  {
    public Department()
    {
      this.Courses = new HashSet<Course>();
    }
    public int DepartmentId { get; set; }
    public string DepartmentName { get; set; }
    public virtual ICollection<Course> Courses { get; set; }
  }
}

Registrar/Controllers/CoursesController.cs
using Microsoft.AspNetCore.Mvc;
using Registrar.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Registrar.Controllers
{
  public class CoursesController : Controller
  {
    private readonly RegistrarContext _db;

    public CoursesController(RegistrarContext db)
    {
      _db = db;
    }

    public ActionResult Index(string CourseSearch)
    {
      List<Course> model = _db.Courses.ToList();
      if(CourseSearch!=null){
          model = _db.Courses.Where(courses => courses.CourseName.Contains(CourseSearch)).ToList();
        }
      return View(model);
    }

    public ActionResult Create()
    {

      // if(department==null){
      // return View()
      //   } else {
      //   _db.Departments.Add(department);
      //   _db.SaveChanges();
      //   }
      ViewBag.DepartmentId = new SelectList(_db.Departments, "DepartmentId", "DepartmentName");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Course course)
    {
      _db.Courses.Add(course);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisCourse = _db.Courses
        .Include(course => course.Students)
        .ThenInclude(join => join.Student)
        .FirstOrDefault(course => course.CourseId == id);
      return View(thisCourse);
    }

    public ActionResult Edit(int id)
    {
      var thisCourse = _db.Courses.FirstOrDefault(course => course.CourseId == id);
      return View(thisCourse);
    }

    [HttpPost]
    public ActionResult Edit(Course course)
    {
      _db.Entry(course).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    public ActionResult AddStudent(int id)
    {
        var thisCourse = _db.Courses.FirstOrDefault(course => course.CourseId == id);
        ViewBag.StudentId = new SelectList(_db.Students, "StudentId", "StudentName");
        return View(thisCourse);
    }
    [HttpPost]
    public ActionResult AddStudent(Course course, int StudentId)
    {
        if (StudentId != 0)
        {
            _db.CourseStudent.Add(new CourseStudent() { CourseId = course.CourseId, StudentId = StudentId });   
        }
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
        var thisCourse = _db.Courses.FirstOrDefault(courses => courses.CourseId == id);
        return View(thisCourse);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
        var thisCourse = _db.Courses.FirstOrDefault(courses => courses.CourseId == id);
        _db.Courses.Remove(thisCourse);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

    public ActionResult DeleteAll()
    {
        var allCourses = _db.Courses.ToList();
        return View();
    }

    [HttpPost, ActionName("DeleteAll")]
        public ActionResult DeleteAllConfirmed()
    {
        var allCourses = _db.Courses.ToList();

    foreach (var course in allCourses)
    {
        _db.Courses.Remove(course);
    }
        _db.SaveChanges();
        return RedirectToAction("Index");
    }
  }
}

Registrar/Controllers/DepartmentsController.cs
using Microsoft.AspNetCore.Mvc;
using Registrar.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Registrar.Controllers
{
  public class DepartmentsController : Controller
  {
    private readonly RegistrarContext _db;

    public DepartmentsController(RegistrarContext db)
    {
      _db = db;
    }

    public ActionResult Index(string DepSearch)
    {
        List<Department> model = _db.Departments.ToList();
        if(DepSearch!=null){
          model = _db.Departments.Where(departments => departments.DepartmentName.Contains(DepSearch)).ToList();
        }
        return View(model);
    }

    public ActionResult Create()
    {
        ViewBag.CourseId = new SelectList(_db.Courses, "CourseId", "CourseName");
        return View();
    }

    [HttpPost]
    public ActionResult Create(Department department)
    {
        _db.Departments.Add(department);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
        Department thisDepartment = _db.Departments.FirstOrDefault(department => department.DepartmentId == id);
        List<Course> foundCourses = _db.Courses.Where(course => course.DepartmentId == id).ToList();
        ViewBag.foundCourses = foundCourses;
        return View(thisDepartment);
    }

    public ActionResult Delete(int id)
    {
      var thisDepartment = _db.Departments.FirstOrDefault(department => department.DepartmentId == id);
      return View(thisDepartment);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisDepartment = _db.Departments.FirstOrDefault(department => department.DepartmentId == id);
      _db.Departments.Remove(thisDepartment);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Edit(int id)
    {
      var thisDepartment = _db.Departments.FirstOrDefault(department => department.DepartmentId == id);
      return View(thisDepartment);
    }

    [HttpPost]
    public ActionResult Edit(Department department)
    {
        _db.Entry(department).State = EntityState.Modified;
        _db.SaveChanges();
        return RedirectToAction("Index");
    }
    public ActionResult AddCourse(int id)
    {
        var thisDepartment = _db.Departments.FirstOrDefault(departments => departments.DepartmentId == id);
        ViewBag.CourseId = new SelectList(_db.Courses, "CourseId", "CourseName");
        return View(thisDepartment);
    }
    [HttpPost]
    public ActionResult AddCourse(Course course, int DepartmentId)
    {
        var thisCourse = _db.Courses.FirstOrDefault(element => element.CourseId == course.CourseId);
        thisCourse.DepartmentId = DepartmentId; //line 83 is true/happened
        _db.Courses.Attach(thisCourse); // prepping for a save
        _db.Entry(thisCourse).Property(element => element.DepartmentId).IsModified = true; // edit modification to db from line 83
        // _db.Entry(thisCourse).State = EntityState.Modified; //not needed
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

      public ActionResult DeleteAll()
        {
            var allDepartments = _db.Departments.ToList();
            return View();
        }

        [HttpPost, ActionName("DeleteAll")]
            public ActionResult DeleteAllConfirmed()
        {
            var allDepartments = _db.Departments.ToList();

        foreach (var department in allDepartments)
        {
            _db.Departments.Remove(department);
        }
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
  }
}

Registrar/Views/Departments/AddCourse.cshtml
@{
  Layout = "_Layout";
}
@model Registrar.Models.Department;
<div class="container card">
<h2>Add a course</h2>
<h4>Add a course to this department: @Html.DisplayFor(model => model.DepartmentName)</h4>

@using(Html.BeginForm())
{
  @Html.HiddenFor(model => model.DepartmentId)

  @Html.Label("Select course")
  @Html.DropDownList("CourseId")

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to departments", "Index")</p>
</div>

Registrar/Views/Departments/Create.cshtml
@{
  Layout = "_Layout";
}

@model Registrar.Models.Department
<div class="container card">
<h4>Add a new department</h4>
@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.DepartmentId)

    @Html.LabelFor(model => model.DepartmentName)
    @Html.TextBoxFor(model => model.DepartmentName)

    @Html.Label("Add course")
    @Html.DropDownList("CourseId")
    <input type="submit" value="Add new department" />
}
<p>@Html.ActionLink("Show all departments", "Index")</p> 
</div>

Registrar/Views/Departments/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Registrar.Models.Department
<div class="container card">
<h2>Are you sure?</h2>

@Html.DisplayNameFor(model => model.DepartmentName) : @Html.DisplayFor(model => model.DepartmentName)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to department list", "Index")
</div>

Registrar/Views/Departments/DeleteAll.cshtml
@{
  Layout = "_Layout";
}
@model List<Registrar.Models.Course>;

<div class="container card">
    <h2>DELETE ALL DEPARTMENTS?</h2>
    <hr>
    @using (Html.BeginForm())
    {
        <button class="btn btn-primary" type="submit" value="DeleteAll">YES</button>
    }
    <br>
    <strong><p>@Html.ActionLink("Back to department list", "Index")</p></strong>
</div>

Registrar/Views/Departments/Details.cshtml
@{
  Layout = "_Layout";
}
@using Registrar.Models
@model Registrar.Models.Department;
<div class="container card">
<h2>Departments Details</h2>

<h3>@Html.DisplayFor(model => model.DepartmentName)</h3>

@if(@Model.Courses.Count == 0)
{
    <p>This department does not belong to any courses</p>
}
else
{
  <h4>Courses this department contains:</h4>
  <ul>
    @foreach(Course course in ViewBag.foundCourses)
    {
        <li>@Html.ActionLink(@course.CourseName, "Details", "Courses", new { id = course.CourseId })</li>
    }
    </ul>
}

<p>@Html.ActionLink("Add course to this department", "AddCourse", "Departments", new { id = Model.DepartmentId })</p>
<p>@Html.ActionLink("Back to departments", "Index")</p>
<p>@Html.ActionLink("Edit department", "Edit", new { id = Model.DepartmentId })</p> 
<p>@Html.ActionLink("Delete department", "Delete", new { id = Model.DepartmentId })</p>
</div>

Registrar/Views/Departments/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Registrar.Models.Department
<div class="container card">
<h2>Edit</h2>

<h4>Edit this department: @Html.DisplayFor(model => model.DepartmentName)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.DepartmentId)
    
    @Html.LabelFor(model => model.DepartmentName)
    @Html.EditorFor(model => model.DepartmentName)

    <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to department list", "Index")</p>
</div>

Registrar/Views/Departments/Index.cshtml
@{
  Layout = "_Layout";
}

@using Registrar.Models;
@model List<Registrar.Models.Department>;
<div class="container card">
<h1>University Departments</h1>
<form>
    <i class="glyphicon glyphicon-search"></i><input type="text" name="DepSearch" placeholder="search and press enter">
</form>

@if (@Model.Count == 0)
{
  <h3>No departments have been added yet!</h3>
} 

@foreach (Department department in Model)
{
  <li>@Html.ActionLink($"{department.DepartmentName}", "Details", new { id = department.DepartmentId })</li>
}

<p>@Html.ActionLink("Add new department", "Create")</p>
<strong><p>@Html.ActionLink("Delete All Departments", "DeleteAll")</p></strong>
</div>